-- MySQL Script generated by MySQL Workbench
-- Mon Jan 20 19:08:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `location_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`lot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lot` (
  `lot_id` INT NOT NULL AUTO_INCREMENT,
  `lot_title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`lot_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`lot_condition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lot_condition` (
  `condition_id` INT NULL AUTO_INCREMENT,
  `condition_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`condition_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`tax_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tax_type` (
  `tax_type_id` INT NOT NULL AUTO_INCREMENT,
  `tax_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tax_type_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sale` (
  `sale_id` INT NOT NULL AUTO_INCREMENT,
  `sale_date` DATE NOT NULL,
  `pre_tax_amount` DECIMAL NOT NULL,
  `tax_amount` DECIMAL NOT NULL,
  `category_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  `tax_type_id` INT NOT NULL,
  `lot_id` INT NOT NULL,
  `lot_condition_id` INT NOT NULL,
  PRIMARY KEY (`sale_id`),
  INDEX `fk_lot_categories_idx` (`category_id` ASC) ,
  INDEX `fk_lot_location1_idx` (`location_id` ASC) ,
  INDEX `fk_sale_tax_type1_idx` (`tax_type_id` ASC) ,
  INDEX `fk_sale_lot1_idx` (`lot_id` ASC) ,
  INDEX `fk_sale_lot_condition1_idx` (`lot_condition_id` ASC) ,
  CONSTRAINT `fk_lot_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lot_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_tax_type1`
    FOREIGN KEY (`tax_type_id`)
    REFERENCES `mydb`.`tax_type` (`tax_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_lot1`
    FOREIGN KEY (`lot_id`)
    REFERENCES `mydb`.`lot` (`lot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_lot_condition1`
    FOREIGN KEY (`lot_condition_id`)
    REFERENCES `mydb`.`lot_condition` (`condition_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER DATABASE mydb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE mydb.lot CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
