# Generated by Django 4.1.3 on 2022-12-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('category', models.CharField(max_length=50)),
                ('lot_title', models.CharField(max_length=100)),
                ('lot_location', models.CharField(max_length=200)),
                ('lot_condition', models.CharField(max_length=200)),
                ('pre_tax_amount', models.PositiveIntegerField()),
                ('tax_name', models.CharField(blank=True, max_length=200)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
